Bear Warrior:    Sarge? You awake? Thought you were a goner... 
Reaver:    Sergeant? Are you finally awake? Thought I'd lost you. 
Reaver:    The portal clearly malfunctioned... I think we ended up on top of Valc. 
Bear Warrior:    The portal just spat us out here... I think we ended up on top of Valc. 
This dirt looks like it could be tunneled through with the proper tool. 
This switch requires an Earth Key to activate the power source. 
This switch requires a Crystal Key to activate the power source. 
Bear Warrior:    Hey look! The Ward is destroying the cultist pentagrams! 
Reaver:    The Ward is going back up! Look at the pentagrams fizzling! 
The switch doesn't seem to work. You hear a distant rumble from outside. 
Bear Warrior:    Damn it! These cultist bastards got all the way up here! 
Reaver:    Oh, no... the cultists have gotten all the way up here. 
(You discover what looks like a crudely drawn map of the surroundings)
(A certain X mark grabs your attention. You copy its location over your own map) 
(You glance over what looks like a crudely drawn map of the surroundings)
(A certain X mark stands out, and you've already copied it into your own map) 
You'll need a proper tool to dig here. 
A magical seal seems to be holding the lever into place. 
A magical seal prevents the switch from being activated. 
The switch seems to not be powered right now. 
This door requires an Earth key to open. 
The glass looks like it was hit with massive force. It could probably break under another blow. 
(The parchment is scribbled with various alchemical formulas.) 
(You spot a note carefully lodged in between the rocks. It's written in human tongue)
If everything went according to plan, you should be reading this message.  Your source was right,
the orc magician stationed here is carrying around one of those enchanted bags.  Had a hard time
stealing it as the orcs seem to be overly jumpy.   Nonetheless, my job here is done.   I have hidden
three notes that will explain how to retrieve the bag.   Don't worry, they won't find it very soon...
The first clue is - CL.  I've hidden the second note behind the chimney, near the two guard towers.
I probably don't have to tell you to memorize this and then burn the note, but just to make sure. 
Our two troublemakers have gotten into a fight again. This time, they've managed to crack one of
the windows in the barracks...     The crystal glass may stand up to its reputation, but we will still
have to replace it. Make sure you make the right requisition next time the supply caravan arrives.
I will be heading out to the dwarven fortress tomorrow to settle a few important matters. I barely
have time to give those rowdy Bear Warriors their due punishment...  their discipline seems to be as
shaky as everything else lately. Nonetheless, I am counting on you to handle things until I return.
Oh, and don't forget to patch up the leaking pipes in the inner courtyard, alright? - Lancer Dendra 
Hey, pass by the archive when you have time, and bring your shovel too. I've heard some strange
noise behind one of the wall panels,  better check to make sure we don't have water leaking in. 
Hey, pass by the archive when you have time, and bring your shovel too. I've heard some strange
noise behind one of the wall panels, better check to make sure we don't have water leaking in. 
Rot. 509, Day 237
First they finished that elevator linking the Dwarven Fortress with Valc, and now the campaign
began. I'm starting to think we won't have any of the bearded fellas coming through here for a
while. I suppose that's less time recording trades and more time reading something interesting. 
Chapter 3 - The Basic Crystals
One of the most common magical crystals found inside the underground is the bright cyan one.
It grows in spiral patterns, and the more the formation coils around, the greater is its age.
It has interesting properties ranging from producing heat through an inner vibration to being
able to attract or reject metal.   The light and warmth generated by this crystal allow for a
lush flora to thrive away from sunlight.   Its use in our technology will be detailed later on.
Yellow crystals are another fairly common sight.     They are usually formed in bundles, but
unlike cyan ones, they do not seem to possess the same ability to grow in time.     Therefore, it
is considered that they are a finite resource, and are regarded as much more valuable. Their
main property is that they store energy which is required to power up our machines. The power
of these crystals is measured by the intensity of the glow  -  a bright core is generally suited
for powering large installations, but is also more unstable.   For this reason, our energy guns
such as Sentry Turrets or Crylances employ depleted shards that have a much duller glow.
Armor Amulets are created from the same crystals, but they are imbued with magical spells.
The process ends up altering the color, but this shall be better detailed in a future chapter. 
MOUNTAIN GATE CONTROLS 
(A journal lies open at the bottom of the chest. It seems to belong to a grunt named Griva)
That swine, Udra, has cheated on the card game again yesterday.  She thinks that just because
she's stronger, she can push everyone around like that. I've bought a Potion of Might, which I'll
keep in the hiding spot.   Let's see how tough she'll be after I slip some of it into my drink before
tonight's rematch. I don't care if Dendra puts the whip on us, Udra simply has to be put in place. 
TO MOUNTAIN PASS 
This door seems to be locked from the other side. 
Lancer Dendra's Log, Rotation 509, Day 238
Seems like I can hardly have any silence around the base this week.  Just as I was about to set
off to the dwarven fortress to negotiate the further trades, I have to deal with Udra stirring
another fight, this time with Griva.   They've managed to crack up one of the windows inside the
barracks but as I went to lay discipline, I've discovered something far more worrying   -  a note.
Hidden between a shutter and an iron panel, and written in Human language. Upon reading it, my
expectations have been confirmed - my bag has been stolen! I've already tasked the Reavers to
search around for other such notes, and devise a plan to ambush and root these rats out. I have
a really bad feeling about this...        I know I should see to this matter by myself and try to find
out where my bag has been hidden but dwarves are keen on punctuality so I'll have to leave now. 
(A scroll lies hidden behind the chimney. You find that it is written in human language)
Good, you've found the second note. Piecing all three together will reveal the location of
a map that will point you the way. You're good with riddles so let's play it safe, shall we?
Your second clue is - OS. The third part lies under the hibernating bear's nose. Good luck. 
(A tiny note lies on the table. It seems to have been written by a human.)
So you've found the last note.  This one should now point you towards the bag's location.
The last clue is - ET.  Search around the basket and you'll find it eventually. Good luck. 
AUTOMATIC DEFENSE
- OUTER SENTRY GUNS - 
AUTOMATIC DEFENSE
- INNER SENTRY GUNS - 
CLOSET 
STORAGE 
SECURITY 
CRYSTAL WARD CONTROL 
LIVING QUARTERS 
REPAIR BAY 
CRYSTAL WARD ACTIVATION
The Crystal Ward may only be deactivated under direct order from the Lancer Council. Should
a powerful magical ritual require to be performed,  the commanding officer will be instructed
directly on when and for how long should the defence be lowered.  Reactivating the ward can be
done following three steps:       first, the commanding officer and her aide will use their keys on
the two switches that control the power crystal sources. Secondly, the maintenance crew must
manually turn on the four support pillars at the ward's base.   The pillars can be activated at
any time, but should not stay idle for hours.  Lastly, the middle switch will activate the ward.
WARNING:  Do not activate if any large scale magic is being performed in Valc or its proximity. 
CRYSTAL WARD ACTIVATION
The Crystal Ward may only be deactivated under direct order from the Lancer Council. Should
a powerful magical ritual require to be performed,  the commanding officer will be instructed
directly on when and for how long should the defence be lowered.  Reactivating the ward can be
done following three steps:       first, the commanding officer and her aide will use their keys on
the two switches that control the power crystal sources. Secondly, the maintenance crew must
manually turn on the four support pillars at the ward's base.   The pillars can be activated at
any time, but should not stay idle for hours.  Lastly, the middle switch will activate the ward.
WARNING:  Do not activate if any large scale magic is being performed in Valc or its proximity. 
I haven't received word from our cultists tasked with taking over the dwarven fortress.
The attack is either still going, or these fools have perished in the snow before they could
even get to draw steel. Mistress Nithriel has specifically ordered to keep this base sealed
off to any visitors,  as it is critical to our ability to teleport reinforcements in.      I have
blocked the switch for the mountain gate with a magical seal. Nobody is to tamper with it. 
I haven't received word from our cultists tasked with taking over the dwarven fortress.
The attack is either still going, or these fools have perished in the snow before they could
even get to draw steel. Mistress Nithriel has specifically ordered to keep this base sealed
off to any visitors,  as it is critical to our ability to teleport reinforcements in.      I have
blocked the switch for the mountain gate with a magical seal. Nobody is to tamper with it. 
(A fancy journal sits on the nightstand. The pages are decorated with earthly symbols)
It's been six days since that Witch, Lith, came here with a Ward deactivation order. I can't help
but wonder what they are doing... the order was indeed signed by their chieftain, Zura, and had
the Council's approval seal on it, but she refused to give out any information about what ritual
was being performed. Clearly it has to be something strong since we need to lower the Ward so it
doesn't tamper with their magic. Dendra didn't seem to care much. I believe she's going through
a hard time keeping the base together, and now she's about to set off to the dwarven fortress.
...perhaps I'm being too judgemental about Witches. After all, nothing bad has happened so far.
The deactivation order expires tomorrow, so I'll have to go turn on the Crystal Ward by myself,
and then I'll probably have some time to help the Reavers find out whoever stole Dendra's bag. 
